name = "invern-be"
compatibility_date = "2025-09-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "INVERN_DB"
database_name = "invern-db"
database_id = "ddf70d9c-9ea3-4279-abe6-614941edfddc"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "STOCK_BUCKET"
bucket_name = "stock-local"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth_kv"

[[kv_namespaces]]
binding = "VALIDATION_KV"
id = "validation_kv"

[[kv_namespaces]]
binding = "STOCK_KV"
id = "stock_kv"
