name = "invern-be"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "STOCK_BUCKET"
bucket_name = "stock-local"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth_kv"

[[kv_namespaces]]
binding = "VALIDATION_KV"
id = "validation_kv"

[[kv_namespaces]]
binding = "STOCK_KV"
id = "stock_kv"

[[d1_databases]]
binding = "INVERN_DB"
database_name = "invern-db"
database_id = "e1b1be5c-cc8f-4c0c-baf1-81e8e5ce48fc"
migrations_dir = "./drizzle"
