name = "invern-be"
compatibility_date = "2024-05-14"

[[d1_databases]]
binding = "INVERN_DB"
database_name = "INVERN_DB"
database_id = "e5193edd-54a6-4b15-8e67-d0bd12b9afd2"

[[r2_buckets]]
binding = "STOCK_BUCKET"
bucket_name = "stock-local"