name = "invern-be"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "STOCK_BUCKET"
bucket_name = "stock-local"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth_kv"

[[kv_namespaces]]
binding = "VALIDATION_KV"
id = "validation_kv"