export const EmailTemplateEnum = {
  CHECKOUT_SUCCESSFUL: 1,
  PASSWORD_RESET_SUCCESSFUL: 5,
  VERIFY_EMAIL: 8,
  SIGNUP_SUCCESSFUL: 7,
  RESET_PASSWORD: 6,
  EMAIL_CHANGED_SUCCESSFULLY: 4,
} as const;
