import { PaymentIntent, StripeEvent } from "@stripe-entity";

export const stripeCheckoutPaymentIntentResultSucceededEventMock: StripeEvent =
  {
    id: "evt_3PtUmyBqKEpmI70R3VdHWmU5",
    object: "event",
    api_version: "2024-04-10",
    created: 1725024177,
    data: {
      object: {
        id: "pi_3PtUmyBqKEpmI70R3vATTu1b",
        object: "payment_intent",
        amount: 500,
        amount_capturable: 0,
        amount_details: {
          tip: {},
        },
        amount_received: 500,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: "automatic_async",
        client_secret:
          "pi_3PtUmyBqKEpmI70R3vATTu1b_secret_YqYnoWgkQeud9HSVptcX1JnFJ",
        confirmation_method: "automatic",
        created: 1725024176,
        currency: "eur",
        customer: "cus_Ql0ogVaZbwlM2I",
        description: null,
        invoice: null,
        last_payment_error: null,
        latest_charge: "ch_3PtUmyBqKEpmI70R3StF00es",
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: "pm_1PtUmxBqKEpmI70RoQ0e9gZZ",
        payment_method_configuration_details: null,
        payment_method_options: {
          card: {
            installments: null,
            mandate_options: null,
            network: null,
            request_three_d_secure: "automatic",
          },
        },
        payment_method_types: ["card"],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: null,
        shipping: {
          address: {
            city: "Lisbon",
            country: "PT",
            line1: "Avenida das Poções",
            line2: "Nr. 3, 18º Trás",
            postal_code: "1234-123",
            state: null,
          },
          carrier: null,
          name: "Mafalda Rodriges",
          phone: null,
          tracking_number: null,
        },
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: "succeeded",
        transfer_data: null,
        transfer_group: null,
      },
    },
    livemode: false,
    pending_webhooks: 1,
    request: {
      id: "req_zyEWgZkKuTfze6",
      idempotency_key: "6b63dc62-4022-4c3c-822e-25fbd32ee7a6",
    },
    type: "payment_intent.succeeded",
  };

export const stripeCheckoutPaymentIntentResultCreatedEventMock: StripeEvent = {
  id: "evt_3PtUmyBqKEpmI70R3B7Zr34n",
  object: "event",
  api_version: "2024-04-10",
  created: 1725024176,
  data: {
    object: {
      id: "pi_3PtUmyBqKEpmI70R3vATTu1b",
      object: "payment_intent",
      amount: 500,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: "automatic_async",
      client_secret:
        "pi_3PtUmyBqKEpmI70R3vATTu1b_secret_YqYnoWgkQeud9HSVptcX1JnFJ",
      confirmation_method: "automatic",
      created: 1725024176,
      currency: "eur",
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: null,
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: "automatic",
        },
      },
      payment_method_types: ["card"],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "requires_payment_method",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: "req_zyEWgZkKuTfze6",
    idempotency_key: "6b63dc62-4022-4c3c-822e-25fbd32ee7a6",
  },
  type: "payment_intent.created",
};

export const stripeCheckoutPaymentIntentResultCanceledEventMock: StripeEvent = {
  id: "evt_3PeSIIBqKEpmI70R0ZRTf3sn",
  object: "event",
  api_version: "2024-04-10",
  created: 1721526042,
  data: {
    object: {
      id: "pi_3PeSIIBqKEpmI70R01cNDAYh",
      object: "payment_intent",
      amount: 2000,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: 1721526042,
      cancellation_reason: "automatic",
      capture_method: "automatic_async",
      client_secret:
        "pi_3PeSIIBqKEpmI70R01cNDAYh_secret_x2CgdSZNXjMVz8trko3AZwHQl",
      confirmation_method: "automatic",
      created: 1721439666,
      currency: "eur",
      customer: "cus_QVTE57thR2BTHJ",
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: "py_3PeSIIBqKEpmI70R0PoneLOD",
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        paypal: {
          preferred_locale: null,
          reference: null,
        },
      },
      payment_method_types: ["paypal"],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: {
        address: {
          city: "Lisbon",
          country: "PT",
          line1: "Avenida das Poções",
          line2: "Nr. 3, 18º Trás",
          postal_code: "1234-123",
          state: null,
        },
        carrier: null,
        name: "Mafalda Rodriges",
        phone: null,
        tracking_number: null,
      },
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "canceled",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: "payment_intent.canceled",
};

export const stripeCheckoutPaymentIntentResultProcessingEventMock: StripeEvent =
  {
    id: "evt_3PeSIIBqKEpmI70R0ZRTf3sn",
    object: "event",
    api_version: "2024-04-10",
    created: 1721526042,
    data: {
      object: {
        id: "pi_3PeSIIBqKEpmI70R01cNDAYh",
        object: "payment_intent",
        amount: 2000,
        amount_capturable: 0,
        amount_details: {
          tip: {},
        },
        amount_received: 0,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: 1721526042,
        cancellation_reason: "automatic",
        capture_method: "automatic_async",
        client_secret:
          "pi_3PeSIIBqKEpmI70R01cNDAYh_secret_x2CgdSZNXjMVz8trko3AZwHQl",
        confirmation_method: "automatic",
        created: 1721439666,
        currency: "eur",
        customer: "cus_QVTE57thR2BTHJ",
        description: null,
        invoice: null,
        last_payment_error: null,
        latest_charge: "py_3PeSIIBqKEpmI70R0PoneLOD",
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: null,
        payment_method_configuration_details: null,
        payment_method_options: {
          paypal: {
            preferred_locale: null,
            reference: null,
          },
        },
        payment_method_types: ["paypal"],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: null,
        shipping: {
          address: {
            city: "Lisbon",
            country: "PT",
            line1: "Avenida das Poções",
            line2: "Nr. 3, 18º Trás",
            postal_code: "1234-123",
            state: null,
          },
          carrier: null,
          name: "Mafalda Rodriges",
          phone: null,
          tracking_number: null,
        },
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: "canceled",
        transfer_data: null,
        transfer_group: null,
      },
    },
    livemode: false,
    pending_webhooks: 1,
    request: {
      id: null,
      idempotency_key: null,
    },
    type: "payment_intent.processing",
  };

export const stripeCheckoutPaymentIntentResultFailedEventMock: StripeEvent = {
  id: "evt_3PeSIIBqKEpmI70R0ZRTf3sn",
  object: "event",
  api_version: "2024-04-10",
  created: 1721526042,
  data: {
    object: {
      id: "pi_3PeSIIBqKEpmI70R01cNDAYh",
      object: "payment_intent",
      amount: 2000,
      amount_capturable: 0,
      amount_details: {
        tip: {},
      },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: 1721526042,
      cancellation_reason: "automatic",
      capture_method: "automatic_async",
      client_secret:
        "pi_3PeSIIBqKEpmI70R01cNDAYh_secret_x2CgdSZNXjMVz8trko3AZwHQl",
      confirmation_method: "automatic",
      created: 1721439666,
      currency: "eur",
      customer: "cus_QVTE57thR2BTHJ",
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: "py_3PeSIIBqKEpmI70R0PoneLOD",
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        paypal: {
          preferred_locale: null,
          reference: null,
        },
      },
      payment_method_types: ["paypal"],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: {
        address: {
          city: "Lisbon",
          country: "PT",
          line1: "Avenida das Poções",
          line2: "Nr. 3, 18º Trás",
          postal_code: "1234-123",
          state: null,
        },
        carrier: null,
        name: "Mafalda Rodriges",
        phone: null,
        tracking_number: null,
      },
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "canceled",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: null,
    idempotency_key: null,
  },
  type: "payment_intent.payment_failed",
};

export const stripeCheckoutPaymentIntentResultSucceededMock: PaymentIntent = {
  id: "pi_3PtUmyBqKEpmI70R3vATTu1b",
  object: "payment_intent",
  amount: 500,
  amount_capturable: 0,
  amount_details: {
    tip: {},
  },
  amount_received: 500,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: "automatic_async",
  client_secret: "pi_3PtUmyBqKEpmI70R3vATTu1b_secret_YqYnoWgkQeud9HSVptcX1JnFJ",
  confirmation_method: "automatic",
  created: 1725024176,
  currency: "eur",
  customer: "cus_Ql0ogVaZbwlM2I",
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: "ch_3PtUmyBqKEpmI70R3StF00es",
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: "pm_1PtUmxBqKEpmI70RoQ0e9gZZ",
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: "automatic",
    },
  },
  payment_method_types: ["card"],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: {
    address: {
      city: "Lisbon",
      country: "PT",
      line1: "Avenida das Poções",
      line2: "Nr. 3, 18º Trás",
      postal_code: "1234-123",
      state: null,
    },
    carrier: null,
    name: "Mafalda Rodriges",
    phone: null,
    tracking_number: null,
  },
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "succeeded",
  transfer_data: null,
  transfer_group: null,
};

export const stripeCheckoutPaymentIntentResultCreatedMock: PaymentIntent = {
  id: "pi_3PtUmyBqKEpmI70R3vATTu1b",
  object: "payment_intent",
  amount: 500,
  amount_capturable: 0,
  amount_details: {
    tip: {},
  },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: "automatic_async",
  client_secret: "pi_3PtUmyBqKEpmI70R3vATTu1b_secret_YqYnoWgkQeud9HSVptcX1JnFJ",
  confirmation_method: "automatic",
  created: 1725024176,
  currency: "eur",
  customer: null,
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: null,
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: "automatic",
    },
  },
  payment_method_types: ["card"],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "requires_payment_method",
  transfer_data: null,
  transfer_group: null,
};

export const stripeCheckoutPaymentIntentResultProcessingMock: PaymentIntent = {
  id: "pi_3PtUmyBqKEpmI70R3vATTu1b",
  object: "payment_intent",
  amount: 500,
  amount_capturable: 0,
  amount_details: {
    tip: {},
  },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: "automatic_async",
  client_secret: "pi_3PtUmyBqKEpmI70R3vATTu1b_secret_YqYnoWgkQeud9HSVptcX1JnFJ",
  confirmation_method: "automatic",
  created: 1725024176,
  currency: "eur",
  customer: null,
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: null,
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: "automatic",
    },
  },
  payment_method_types: ["card"],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "requires_payment_method",
  transfer_data: null,
  transfer_group: null,
};

export const stripeCheckoutPaymentIntentResultCanceledMock: PaymentIntent = {
  id: "pi_3PeSIIBqKEpmI70R01cNDAYh",
  object: "payment_intent",
  amount: 2000,
  amount_capturable: 0,
  amount_details: {
    tip: {},
  },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: 1721526042,
  cancellation_reason: "automatic",
  capture_method: "automatic_async",
  client_secret: "pi_3PeSIIBqKEpmI70R01cNDAYh_secret_x2CgdSZNXjMVz8trko3AZwHQl",
  confirmation_method: "automatic",
  created: 1721439666,
  currency: "eur",
  customer: "cus_QVTE57thR2BTHJ",
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: "py_3PeSIIBqKEpmI70R0PoneLOD",
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: {
    paypal: {
      preferred_locale: null,
      reference: null,
    },
  },
  payment_method_types: ["paypal"],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: {
    address: {
      city: "Lisbon",
      country: "PT",
      line1: "Avenida das Poções",
      line2: "Nr. 3, 18º Trás",
      postal_code: "1234-123",
      state: null,
    },
    carrier: null,
    name: "Mafalda Rodriges",
    phone: null,
    tracking_number: null,
  },
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "canceled",
  transfer_data: null,
  transfer_group: null,
};

export const stripeCheckoutPaymentIntentResultFailedMock: PaymentIntent = {
  id: "pi_3PeSIIBqKEpmI70R01cNDAYh",
  object: "payment_intent",
  amount: 2000,
  amount_capturable: 0,
  amount_details: {
    tip: {},
  },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: 1721526042,
  cancellation_reason: "automatic",
  capture_method: "automatic_async",
  client_secret: "pi_3PeSIIBqKEpmI70R01cNDAYh_secret_x2CgdSZNXjMVz8trko3AZwHQl",
  confirmation_method: "automatic",
  created: 1721439666,
  currency: "eur",
  customer: "cus_QVTE57thR2BTHJ",
  description: null,
  invoice: null,
  last_payment_error: null,
  latest_charge: "py_3PeSIIBqKEpmI70R0PoneLOD",
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: {
    paypal: {
      preferred_locale: null,
      reference: null,
    },
  },
  payment_method_types: ["paypal"],
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: {
    address: {
      city: "Lisbon",
      country: "PT",
      line1: "Avenida das Poções",
      line2: "Nr. 3, 18º Trás",
      postal_code: "1234-123",
      state: null,
    },
    carrier: null,
    name: "Mafalda Rodriges",
    phone: null,
    tracking_number: null,
  },
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "canceled",
  transfer_data: null,
  transfer_group: null,
};
