interface Env {
  AUTH_KV: KVNamespace;
  BACKOFFICE_HOST: string;
  CACHE_API_EMAIL: string;
  CACHE_API_KEY: string;
  COUNTRIES_BUCKET: R2Bucket;
  COUNTRIES_HOST: string;
  DEFAULT_IV: string;
  DOMAIN: string;
  ENCRYPTION_KEY: string;
  ENV: string;
  FRONTEND_HOST: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REDIRECT_URI: string;
  HONEYCOMB_API_KEY: string;
  HONEYCOMB_DATASET: string;
  IMAGES_HOST: string;
  INSERT_TEST_DATA_SECRET: string;
  INVERN_DB: D1Database;
  LOGGER_LEVEL: string;
  REFRESH_TOKEN_SECRET: string;
  SALT: string;
  BREVO_API_KEY: string;
  BREVO_DOMAIN: string;
  BREVO_NAME: string;
  SETUP_COUNTRIES_SECRET: string;
  SETUP_STOCK_SECRET: string;
  STOCK_BUCKET: R2Bucket;
  STOCK_KV: KVNamespace;
  STOCK_HOST: string;
  STRIPE_API_KEY: string;
  STRIPE_CHECKOUT_SECRET: string;
  STRIPE_ENV: string;
  STRIPE_PAYMENT_SECRET: string;
  TOKEN_SECRET: string;
  TURSO_AUTH_TOKEN: string;
  TURSO_CONNECTION_URL: string;
  VALIDATION_KV: KVNamespace;
  ZONE_ID: string;
}

export default Env;
